---
name: release-networklookup

on: push
  push:
    paths:
      - 'nl.siebjee.networklookup/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd nl.siebjee.networklookup
          zip -r ../nl.siebjee.networklookup.alfredworkflow *
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: nl.siebjee.networklookup.alfredworkflow

---
name: release-github

on: push
  push:
    paths:
      - 'nl.siebjee.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd nl.siebjee.github
          zip -r ../nl.siebjee.github.alfredworkflow *
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: nl.siebjee.github.alfredworkflow

---
name: release-nmap

on: push
  push:
    paths:
      - 'nl.siebjee.nmap/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd nl.siebjee.nmap
          zip -r ../nl.siebjee.nmap.alfredworkflow *
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: nl.siebjee.nmap.alfredworkflow

---
name: release-slack

on: push
  push:
    paths:
      - 'nl.siebjee.slack/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd nl.siebjee.slack
          zip -r ../nl.siebjee.slack.alfredworkflow *
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: nl.siebjee.slack.alfredworkflow
